version: '2'

services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DATABASE_CONNECTION_STRING: mongodb://mongo:27017/
  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
